Repository UnicornGlobal/data-table, pull requests merged in 2020-02, with the labels that each got.

#221 Feat/enhancements
  package-lock.json
  package.json
  src/DataTable.vue
  src/components/TableData.vue
  src/components/TableRow.vue
  src/components/TableRowOption.vue
  test/specs/components/TableData.spec.js
  test/specs/components/TableRow.spec.js
  test/specs/components/TableRowOption.spec.js
Labels: size/L, ✅ Approved

#222 Add ability to provide component events as a callback
  src/components/TableRowOption.vue
  test/specs/components/TableRowOption.spec.js
Labels: size/M, ✅ Approved

#223 Dropdown Filtering and Enhancements
  package-lock.json
  package.json
  src/DataTable.vue
  src/components/FilterCheckbox.vue
  src/components/FilterDropdown.vue
  src/components/Filtering.vue
  src/components/TableBody.vue
  src/components/TableData.vue
  src/components/TableHeaders.vue
  src/components/TableLinkRow.vue
  src/components/TableRow.vue
  src/components/TableRowOption.vue
  test/specs/DataTable.spec.js
Labels: size/L, 🔍 Ready for Review
