Repository UnicornGlobal/data-table, pull requests merged in 2020-03, with the labels that each got.

#226 Fix alignment of headers
  package-lock.json
  src/components/TableHeaders.vue
Labels: size/XS, ✅ Approved

#228 Allow dropdown filters to process data before comparing
  package-lock.json
  package.json
  src/DataTable.vue
  src/components/Filtering.vue
  test/specs/DataTable.spec.js
  test/specs/components/FilterNumberRange.spec.js
  test/specs/components/TableData.spec.js
Labels: size/S, 🔍 Ready for Review

#230 Header Sorting
  package-lock.json
  package.json
  src/DataTable.vue
  src/components/TableData.vue
  src/components/TableHeaders.vue
Labels: size/M, 🔍 Ready for Review

#231 Insensitive sorting
  package-lock.json
  package.json
  src/DataTable.vue
Labels: size/S, 🔍 Ready for Review
